### ISSUE TITLE
Documentación de como iniciar el proyecto

### ISSUE THREAD

**Issue by dmouse** [phpmx/phpmexico#10]

**Comment by gueroverde** [comment]
Para iniciar el proyecto actualmente el contenedor no cuenta con nodejs por ende no se pueden instalar las dependencias js desde dentro del contenedor, que es lo que deberianos hacer, Agregar node a la imagen de docker o señalar que para levantar el proytecto se instalen estas dependencias desde fuera? @dmouse

**Comment by jashk** [comment]
Hola @gueroverde,

Creo que podemos crear un archivo docker-composer.cli.yml solo con lo necesario para poder hacer el build de los assets

```
##docker-compose.cli.yml
version: "3.7"
services:
  yarn:
    image: node:10-slim
    init: true
    volumes:
      - .:/var/www/html
      - yarn-cache:/root/.cache/yarn/v1
    entrypoint: yarn

volumes:
  yarn-cache:
    name: yarn-cache 
```


Ejecutarlo así:
```
docker-compose -f docker-compose.cli.yml run --rm yarn install
docker-compose -f docker-compose.cli.yml run --rm yarn build
```
